
import conexao.ConexaoEstoque;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2830482221001
 */
public class ProdutoJ extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoJ
     */
    public ProdutoJ() {
        initComponents();
        preencherComboCategoria();
    }
       private void limparFormulario() 
    {
        txtIdProd.setText("");
        txtProdNome.setText("");
        txtProdPreco.setText("");
        txtProdBarras.setText("");
    }
       
       public void preencherComboCategoria(){
           CategoriaDAO cDao = new CategoriaDAO();
           List<Categoria> listaC = cDao.getCategoria();
           for(Categoria c : listaC){
               cmbCategoria.addItem(c);
           }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        txtProdNome = new javax.swing.JTextField();
        txtProdPreco = new javax.swing.JTextField();
        txtProdBarras = new javax.swing.JTextField();
        btnProdSalvar = new javax.swing.JButton();
        btnProdEditar = new javax.swing.JButton();
        btnProdExcluir = new javax.swing.JButton();
        btnProdConsultar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PRODUTOS");

        jLabel2.setText("Nome: ");

        jLabel3.setText("ID:");

        jLabel4.setText("Preço:");

        jLabel5.setText("Categoria:");

        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        jLabel6.setText("Cod. de Barras");

        btnProdSalvar.setText("Salvar");
        btnProdSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdSalvarActionPerformed(evt);
            }
        });

        btnProdEditar.setText("Editar");
        btnProdEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdEditarActionPerformed(evt);
            }
        });

        btnProdExcluir.setText("Excluir");
        btnProdExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdExcluirActionPerformed(evt);
            }
        });

        btnProdConsultar.setText("Consultar");
        btnProdConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdConsultarActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastrar");

        jMenuItem1.setText("Categoria");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Fornecedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdNome)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnProdSalvar)
                        .addGap(26, 26, 26)
                        .addComponent(btnProdConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnProdEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnProdExcluir)))
                .addGap(27, 27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCategoria, txtProdBarras, txtProdNome, txtProdPreco});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnProdConsultar, btnProdEditar, btnProdExcluir, btnProdSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProdPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProdBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdSalvar)
                    .addComponent(btnProdEditar)
                    .addComponent(btnProdExcluir)
                    .addComponent(btnProdConsultar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CategoriaJ c = new CategoriaJ();
       c.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       FornecedorJ f = new FornecedorJ();
       f.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ClienteJ cli = new ClienteJ();
       cli.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnProdSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdSalvarActionPerformed
        Categoria c = (Categoria) cmbCategoria.getSelectedItem();
        Produtos p = new Produtos();
        p.setNome(txtProdNome.getText());
        p.setPreco(Double.parseDouble(txtProdPreco.getText()));
        p.setCategoria(c.getIdCategoria());
        p.setCodBarras(Integer.parseInt(txtProdBarras.getText()));
        
       ProdutoDAO pDAO = new ProdutoDAO();
        pDAO.inserir(p);
        JOptionPane.showMessageDialog(null, "Dados inseridos com sucesso");
        limparFormulario();
    }//GEN-LAST:event_btnProdSalvarActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
 
           
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnProdConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdConsultarActionPerformed
        Categoria c = (Categoria) cmbCategoria.getSelectedItem();
        int idProduto = Integer.parseInt(txtIdProd.getText());
        ProdutoDAO pDAO = new ProdutoDAO();
  
        
        Produtos p = pDAO.getProdutos(idProduto);
        if(p==null){
            txtProdNome.setText("");
            JOptionPane.showMessageDialog(this,"Produto não encontrado");    
        }else{

            txtProdNome.setText(p.getNome());
            txtProdPreco.setText(String.valueOf(p.getPreco()));
           
            cmbCategoria.setSelectedItem(c.getIdCategoria());
            txtProdBarras.setText(String.valueOf(p.getCodBarras()));
        }
    }//GEN-LAST:event_btnProdConsultarActionPerformed

    private void btnProdEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdEditarActionPerformed
        Categoria c = (Categoria) cmbCategoria.getSelectedItem();
        Produtos p = new Produtos();
        p.setId(Integer.parseInt(txtIdProd.getText()));
        p.setNome(txtProdNome.getText());
        p.setPreco(Double.valueOf(txtProdPreco.getText()));
        p.setCategoria(c.getIdCategoria());
        p.setCodBarras(Integer.parseInt(txtProdBarras.getText()));
       
        
       ProdutoDAO pDAO = new ProdutoDAO();
        pDAO.editar(p);
        JOptionPane.showMessageDialog(this,"Dados atualizados com sucesso");
        limparFormulario();
                                              
   
    }//GEN-LAST:event_btnProdEditarActionPerformed

    private void btnProdExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir? ", "Exclusão", JOptionPane.YES_NO_OPTION);
      
      if(resposta == JOptionPane.YES_OPTION){
      ProdutoDAO pDAO = new ProdutoDAO();
         pDAO.excluir(Integer.parseInt(txtIdProd.getText()));
        JOptionPane.showMessageDialog(this,"Dados excluidos com sucesso");
        limparFormulario();
      }
    }//GEN-LAST:event_btnProdExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdConsultar;
    private javax.swing.JButton btnProdEditar;
    private javax.swing.JButton btnProdExcluir;
    private javax.swing.JButton btnProdSalvar;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtProdBarras;
    private javax.swing.JTextField txtProdNome;
    private javax.swing.JTextField txtProdPreco;
    // End of variables declaration//GEN-END:variables
}
